image: docker:latest

services:
  - docker:dind

before_script:
  - docker info 1>/dev/null 2>/dev/null || export DOCKER_HOST="tcp://localhost:2375"
  # - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD

build_for_latest:
  stage: build
  # variables:
  #   DOCKER_HOST: tcp://localhost:2375
  script:
    - docker build --pull -t $DOCKER_HUB_USER/"$CI_PROJECT_NAME:latest" .
    - docker push $DOCKER_HUB_USER/"$CI_PROJECT_NAME:latest"
  only:
    - master

build_for_tags:
  stage: build
  # variables:
  #   DOCKER_HOST: tcp://localhost:2375
  script:
    - docker build --pull -t $DOCKER_HUB_USER/"$CI_PROJECT_NAME:$CI_COMMIT_TAG" .
    - docker push $DOCKER_HUB_USER/"$CI_PROJECT_NAME:$CI_COMMIT_TAG"
  only:
    - tags
